version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/express-app
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 3000
      runas: ubuntu
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 3000
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 3000
      runas: ubuntu